development: true
database: 'postgres://goshop:goshop@localhost:5432/goshop'
listenOnPort: '127.0.0.1:8080'
templateDirectory: '/home/vikesh/go/src/net.vikesh/goshop/templates/*'
writeTimeout: 10
readTimeout: 5